
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'What directory we are in ?'

- script: ls -la
  displayName: 'What files are in this folder?'

- script: dotnet build
  displayName: 'dotnet build'
  workingDirectory: $(solutionDir)

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: 'dotnet publish -o $(build.artifactStagingDirectory)'
  workingDirectory: $(solutionDir)