
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet build
  displayName: 'dotnet build'

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: 'dotnet publish -o $(build.artifactStagingDirectory)'
  workingDirectory: $(solutionDir)